spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bankdb
    username: root
    password: root123

  mvc:
    view:
      prefix: /
      suffix: .html
debug: true

dxc:
  greet:
    message: hello

---

spring:
  config:
    activate:
      on-profile: qa

dxc:
  greet:
    message: hello-QA
